services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - auth-network

  migrator:
    build: 
      context: DatabaseMigrator
      dockerfile: Dockerfile
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      DB_CONNECTION: Host=auth-db;Port=5432;Database=authdb;Username=authuser;Password=authpassword
      RESET_SCHEMA: "true" # only in dev when you want to "wipe"
    volumes:
      - ./db/migrations:/app/sql:ro
    networks:
      - auth-network
    restart: "no"  # run once and stop

  auth-service:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: auth-service
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    networks:
      - auth-network

volumes:
  auth_data:

networks:
  auth-network:
