namespace auth_service.Models;

public class WhitelistEntry
{
    // Id is generated by the database
    public int Id { get; set; }
    // List of emails instead of a single student number
    public List<string> Emails { get; set; } = new();
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    // Team name is now included in the entry
    public string TeamName { get; set; } = string.Empty;
}